#!/bin/bash

source ~/.config/dev-scripts/_colours.sh
source ~/.config/dev-scripts/_functions.sh

RUN_BUILD=0
RUN_QUEUE=0
RUN_NPM=0
RUN_STOP=2
RUN_BASH=2
RUN_IDE=2
RUN_DEFAULT=2
OPTIND=1

USAGE="Open a project that uses Laravel Sail

${BOLD}Usage${ENDCOLOR}:
${CODE}dev [options] <project>${ENDCOLOR}

${BOLD}Help Options${ENDCOLOR}:
 ${CODE}-h${ENDCOLOR}   Show this ${GREEN}h${ENDCOLOR}elp and exit
 ${CODE}-l${ENDCOLOR}   Show a ${GREEN}l${ENDCOLOR}ist of available projects and exit

${BOLD}Running Options${ENDCOLOR}:
 ${CODE}-b${ENDCOLOR}   Do a ${GREEN}b${ENDCOLOR}uild before starting the containers
 ${CODE}-i${ENDCOLOR}   Open the ${GREEN}i${ENDCOLOR}de in the target directory (default)
 ${CODE}-I${ENDCOLOR}   Negate ${CODE}-i${ENDCOLOR} (don't open the IDE)
 ${CODE}-n${ENDCOLOR}   Run ${GREEN}n${ENDCOLOR}pm in development mode
 ${CODE}-q${ENDCOLOR}   Run a ${GREEN}q${ENDCOLOR}ueue worker
 ${CODE}-s${ENDCOLOR}   Open a ${GREEN}s${ENDCOLOR}hell once it the containers have started (default)
 ${CODE}-S${ENDCOLOR}   Negate ${CODE}-s${ENDCOLOR} (don't open a shell)
 ${CODE}-c${ENDCOLOR}   Stop any running sail ${GREEN}c${ENDCOLOR}ontainers (default)
 ${CODE}-C${ENDCOLOR}   Negate ${CODE}-c${ENDCOLOR} (don't stop running containers)
 ${CODE}-d${ENDCOLOR}   Run ${GREEN}d${ENDCOLOR}efault settings (equivalent of ${CODE}-sci${ENDCOLOR})
 ${CODE}-D${ENDCOLOR}   Negate ${CODE}-d${ENDCOLOR}
"

show_projects() {
    EXIT_CODE="${@:-0}"

    declare -A ALL
    mn=-1
    mp=-1

    for p in $(dev-sail); do
        n="${p##*/}"
        if [ ${#n} -gt $mn ]; then mn=${#n}; fi
        if [ ${#p} -gt $mp ]; then mp=${#p}; fi
        ALL[$n]=$p
    done;

    tpl=$(printf "${GREEN}| ${ENDCOLOR}%%s%%-%ds ${GREEN}| ${ENDCOLOR}%%s%%-%ds ${GREEN}|\\\n" $mn $mp)
    sep=$(printf "$tpl" "${GREEN}" "" "${GREEN}" "" | tr " " "=" | tr "|" "+")
    
    echo -e "There are ${GREEN}${#ALL[@]}${ENDCOLOR} available project(s):"

    echo -e "${sep}"
    printf "$tpl" $(echo -e "${BOLD}") "Project" $(echo -e "${BOLD}") "Path"
    echo -e "${sep}"

    for p in $( <<< "${!ALL[@]}" tr ' ' '\n' | sort ) ; do
        printf "$tpl" $(echo -e "${CODE}") "$p" $(echo -e "${CODE}") "${ALL[$p]}"
    done;
    
    echo -e "${sep}"

    exit $EXIT_CODE
}

while getopts 'hldDbqiInsScC' OPTION
do
    case "${OPTION}" in
        h) show_help ;;
        l) show_projects ;;
        d) RUN_DEFAULT=1 ;;
        D) RUN_DEFAULT=0 ;;
        b) RUN_BUILD=1 ;;
        q) RUN_QUEUE=1 ;;
        i) RUN_IDE=1 ;;
        I) RUN_IDE=0 ;;
        n) RUN_NPM=1 ;;
        s) RUN_BASH=1 ;;
        S) RUN_BASH=0 ;;
        c) RUN_STOP=1 ;;
        C) RUN_STOP=0 ;;
        ?)
            echo "Invalid option"
            exit 0
            ;;
    esac
done

if [ $RUN_DEFAULT -eq 2 ]; then RUN_DEFAULT=1; fi
if [ $RUN_IDE -eq 2 ]; then RUN_IDE=$RUN_DEFAULT; fi
if [ $RUN_BASH -eq 2 ]; then RUN_BASH=$RUN_DEFAULT; fi
if [ $RUN_STOP -eq 2 ]; then RUN_STOP=$RUN_DEFAULT; fi

missing_binary 'kitty'
missing_file "${HOME}/.config/kitty/sail.conf"

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

PROJECT="${@}"

if [ -z "$PROJECT" ]; then
    echo -e "${RED}Missing project!${ENDCOLOR}"
    show_help 2
fi

ALL_PROJECTS=($(dev-sail))

FOUND_PROJECTS=()

echo -e "Searching for project: ${CODE}${PROJECT}${ENDCOLOR}"

for e in "${ALL_PROJECTS[@]}"; do
    if [[ "$e" =~ ^.*"${PROJECT}".*$ ]]; then
	    FOUND_PROJECTS+=("${e}")
    fi
done

if [ "${#FOUND_PROJECTS[@]}" -ne 1 ]; then
    echo -e "Found ${RED}${#FOUND_PROJECTS[@]}${ENDCOLOR} projects matching ${CODE}${PROJECT}${ENDCOLOR}"
    for p in "${FOUND_PROJECTS[@]}" ; do
        echo -e " - ${CODE}${p}${ENDCOLOR}"
    done
    exit 2;
fi

echo -e "Found project ${GREEN}${PROJECT}${ENDCOLOR} at ${CODE}${FOUND_PROJECTS[0]}${ENDCOLOR}"

export PROJECT="${FOUND_PROJECTS[0]}"

cd "${PROJECT}"

if [ $RUN_STOP -eq 0 ]; then
    dev-stop
fi
if [ $RUN_BUILD -eq 1 ]; then 
    sail build
fi

export PROJECT=$PROJECT
export RUN_BASH=$RUN_BASH
export RUN_NPM=$RUN_NPM
export RUN_QUEUE=$RUN_QUEUE

if [ $RUN_IDE -eq 1 ]; then
    missing_binary 'phpstorm'
    nohup phpstorm "$PROJECT" > /dev/null 2>&1 &
fi

nohup kitty --session sail.conf > /dev/null 2>&1 &
