#!/bin/bash

declare -A ALL

for p in $(dev-sail); do
  if [ ! -z "${p##*/}" ]; then ALL["${p##*/}"]=$p ; fi
done

PROJECTS=()

for p in $( <<< "${!ALL[@]}" tr ' ' '\n' | sort ) ; do
  PROJECTS+=("FALSE $p ${ALL[$p]}")
done

PROJECT=$( <<< "${PROJECTS[@]}" tr ' ' '\n' | zenity --width=800 --height=600 --list --radiolist --column="Select" --column="Project" --column="Path" --print-column="2" )

if [[ "$PROJECT" =~ ^(-1|[015])?$ ]]; then
  zenity --error --text="Could not open project"
  exit 1;
fi

OPTIONS=(
    "FALSE b Run_Sail_Build"
    "FALSE q Run_Queue"
    "FALSE n Run_Vite"
    "TRUE s Run_Shell"
    "TRUE i Open_IDE"
    "TRUE c Stop_sail_containers"
)

FLAGS=$( <<< "${OPTIONS[@]}" tr ' ' '\n' | tr '_' ' ' | zenity --width=800 --height=600 --list --checklist --column="Select" --column="Flag" --column="Option" --separator='' --print-column="2" )

if [[ "$FLAGS" =~ ^(-1|[015])$ ]]; then
  zenity --error --text="Cancelled opening project"
  exit 1;
elif [ -z $FLAGS ]; then
  dev -D $PROJECT
else
  eval "$(dev -D${FLAGS} ${PROJECT})"
fi
