#!/bin/bash

source ~/.config/dev-scripts/_colours.sh
source ~/.config/dev-scripts/_functions.sh

DRY_RUN=0
USAGE="Stop all currently running sail environments.

${BOLD}Usage:${ENDCOLOR}
${CODE}dev-stop [options]${ENDCOLOR}

${BOLD}Help Options${ENDCOLOR}:
 ${CODE}-h${ENDCOLOR}   Show this ${GREEN}h${ENDCOLOR}elp and exit

${BOLD}Running Options${ENDCOLOR}:
 ${CODE}-d${ENDCOLOR}   Do a ${GREEN}d${ENDCOLOR}ry run (show running containers and exit)"

while getopts 'dh' OPTION
do
    case "${OPTION}" in
        h) show_help ;;
        d) DRY_RUN=1 ;;
        *) ;;
    esac
done

ALL_PROJECTS=$(dev-sail)
RUNNING=$(dev-running)
OTHERS=()
declare -A RUNNING_ENVS

for e in ${RUNNING[@]}; do
    found=0
    for d in ${ALL_PROJECTS[@]}; do
        if [[ "${d}" == *"${e}" ]]; then
            RUNNING_ENVS["$e"]="${d}"
	    found=1
	fi
    done
    if [ $found -eq 0 ]; then
        OTHERS+=("${e}")
    fi
done


if [ "${#RUNNING_ENVS[@]}" -gt 0 ]; then
    echo -e "Found ${GREEN}${#RUNNING_ENVS[@]}${ENDCOLOR} sail environment(s) running:"
    for e in ${!RUNNING_ENVS[@]}; do
        dir="${RUNNING_ENVS[$e]}"
        echo -e " - ${CODE}${e}${ENDCOLOR} (running from ${CODE}${dir}${ENDCOLOR})"
    done
    if [ $DRY_RUN -eq 0 ]; then
        for e in ${!RUNNING_ENVS[@]}; do
            dir="${RUNNING_ENVS[$e]}"
            cd "${dir}"
            echo -e "${RED}STOPPING ${CODE}${e}${ENDCOLOR}..."
            vendor/bin/sail down
            echo -e "${GREEN}DONE${ENDCOLOR}"
        done
    fi
fi

if [ "${#OTHERS[@]}" -gt 0 ]; then
    echo -e "Found ${RED}${#OTHERS[@]}${ENDCOLOR} other docker-compose environment(s) running:"
    for o in "${OTHERS[@]}"; do
      echo -e " - ${CODE}${o}${ENDCOLOR}"
    done
fi
